# Speech Recognition - Sesi 1
## Introduction to Python & NumPy

**Binus University | Speech Recognition Laboratory**

---

### Outline
| Bagian | Topik |
|---|---|
| 1 | Python: Output, Variable, Input, Operator |
| 2 | Python: Selection & Repetition |
| 3 | Python: Function |
| 4 | Python: Built-in Data Structure (List, Tuple, Set, Dictionary) |
| 5 | Python: Slicing |
| 6 | NumPy: Array, Atribut, & Array Generator |
| 7 | NumPy: Indexing, Slicing, & Operasi |
| 8 | NumPy: Stacking (vstack, hstack) |

> **Kenapa Python & NumPy untuk Speech Recognition?**
> Sinyal suara pada dasarnya adalah **deretan angka** (amplitudo per satuan waktu).
> NumPy adalah tools standar untuk mengolah deretan angka tersebut secara cepat dan efisien.

---
# Bagian 1 - Output, Variable, Input, & Operator

## 1.1 Output dengan `print()`

`print()` digunakan untuk menampilkan sesuatu ke layar.

In [1]:
# Cara paling sederhana
print("Hello, Speech Recognition!")

# print bisa menerima beberapa nilai sekaligus, dipisah koma
print("Sample rate:", 16000, "Hz")

# sep = pemisah antar nilai, end = penutup baris
print("A", "B", "C", sep=" - ")
print("Baris ini", end=" ")
print("nyambung dengan baris sebelumnya")

Hello, Speech Recognition!
Sample rate: 16000 Hz
A - B - C
Baris ini nyambung dengan baris sebelumnya


## 1.2 Variable & Tipe Data

Variable adalah wadah untuk menyimpan nilai. Python bersifat **dynamic typing**:
kita tidak perlu menuliskan tipe datanya, Python menebak sendiri dari nilainya.

In [2]:
nama       = "Stanley"     # str   (teks)
umur       = 21            # int   (bilangan bulat)
durasi     = 3.75          # float (bilangan desimal)
is_student = True          # bool  (True / False)

print(nama, type(nama))
print(umur, type(umur))
print(durasi, type(durasi))
print(is_student, type(is_student))

Stanley <class 'str'>
21 <class 'int'>
3.75 <class 'float'>
True <class 'bool'>


### f-string (formatted string)
Cara paling rapi untuk menggabungkan teks dengan variable: tambahkan huruf `f` di depan string,
lalu tulis variable di dalam kurung kurawal `{}`.

In [3]:
print(f"Halo, nama saya {nama} dan umur saya {umur} tahun.")

# :.2f artinya tampilkan sebagai float dengan 2 angka di belakang koma
print(f"Durasi audio: {durasi:.2f} detik")

# ekspresi juga boleh ditulis langsung di dalam kurung kurawal
print(f"Total sample: {durasi * 16000:.0f}")

Halo, nama saya Stanley dan umur saya 21 tahun.
Durasi audio: 3.75 detik
Total sample: 60000


## 1.3 Input dengan `input()`

`input()` membaca ketikan user. **Hasilnya SELALU bertipe `str`**, jadi kalau butuh angka
harus dikonversi dulu dengan `int()` atau `float()`.

In [4]:
# Dijalankan saat demo di kelas (akan memunculkan kotak isian di atas)
# nama_user = input("Masukkan nama Anda: ")
# umur_user = int(input("Masukkan umur Anda: "))
# print(f"Halo {nama_user}, tahun depan umur Anda {umur_user + 1}")

# Simulasi supaya notebook tetap bisa di-run tanpa interaksi:
nama_user = "Mahasiswa"
umur_user = int("20")          # konversi str -> int
print(f"Halo {nama_user}, tahun depan umur Anda {umur_user + 1}")

Halo Mahasiswa, tahun depan umur Anda 21


## 1.4 Operator

| Jenis | Operator |
|---|---|
| Aritmatika | `+`  `-`  `*`  `/`  `//` (bagi bulat)  `%` (sisa bagi)  `**` (pangkat) |
| Perbandingan | `==`  `!=`  `>`  `<`  `>=`  `<=` |
| Logika | `and`  `or`  `not` |

In [5]:
a, b = 17, 5

print("a + b  =", a + b)
print("a - b  =", a - b)
print("a * b  =", a * b)
print("a / b  =", a / b)     # hasil selalu float
print("a // b =", a // b)    # pembagian dibulatkan ke bawah
print("a % b  =", a % b)     # sisa bagi
print("a ** 2 =", a ** 2)    # pangkat

a + b  = 22
a - b  = 12
a * b  = 85
a / b  = 3.4
a // b = 3
a % b  = 2
a ** 2 = 289


In [6]:
# Operator perbandingan -> menghasilkan bool
print("a > b   :", a > b)
print("a == b  :", a == b)

# Operator logika -> menggabungkan beberapa kondisi
print("(a > b) and (b > 0) :", (a > b) and (b > 0))
print("(a < b) or  (b > 0) :", (a < b) or  (b > 0))
print("not (a > b)         :", not (a > b))

a > b   : True
a == b  : False
(a > b) and (b > 0) : True
(a < b) or  (b > 0) : True
not (a > b)         : False


---
# Bagian 2 - Selection & Repetition

## 2.1 Selection (`if` / `elif` / `else`)

Digunakan untuk mengambil keputusan. Perhatikan **indentasi (4 spasi)** - di Python,
indentasi menentukan blok kode, bukan kurung kurawal.

In [7]:
nilai = 82

if nilai >= 85:
    grade = "A"
elif nilai >= 75:
    grade = "B"
elif nilai >= 65:
    grade = "C"
else:
    grade = "D"

print(f"Nilai {nilai} -> Grade {grade}")

Nilai 82 -> Grade B


In [8]:
# Contoh kasus: mengecek kualitas rekaman audio
sample_rate = 16000

if sample_rate >= 44100:
    print("Kualitas CD - cocok untuk musik")
elif sample_rate >= 16000:
    print("Kualitas standar - cocok untuk speech recognition")
else:
    print("Kualitas rendah - kemungkinan akurasi menurun")

# Bentuk singkat (ternary): <nilai_jika_benar> if <kondisi> else <nilai_jika_salah>
status = "Lulus" if nilai >= 65 else "Tidak Lulus"
print("Status:", status)

Kualitas standar - cocok untuk speech recognition
Status: Lulus


## 2.2 Repetition - `for`

`for` dipakai untuk mengulang sebanyak jumlah item pada suatu koleksi.
`range(start, stop, step)` menghasilkan deret angka (`stop` **tidak** ikut).

In [9]:
# range(5) -> 0,1,2,3,4
for i in range(5):
    print("Iterasi ke-", i)

print("---")

# range(start, stop, step)
for i in range(1, 10, 2):
    print(i, end=" ")

Iterasi ke- 0
Iterasi ke- 1
Iterasi ke- 2
Iterasi ke- 3
Iterasi ke- 4
---
1 3 5 7 9 

In [10]:
kata = ["halo", "selamat", "pagi"]

# Looping langsung pada list
for k in kata:
    print(k.upper())

print("---")

# enumerate() memberi index + nilai sekaligus
for idx, k in enumerate(kata):
    print(f"{idx}: {k} ({len(k)} huruf)")

HALO
SELAMAT
PAGI
---
0: halo (4 huruf)
1: selamat (7 huruf)
2: pagi (4 huruf)


## 2.3 Repetition - `while`, `break`, `continue`

`while` mengulang **selama** kondisi masih `True`.

In [11]:
n = 5
while n > 0:
    print(n, end=" ")
    n -= 1       # WAJIB ada perubahan, kalau tidak -> infinite loop
print("Selesai!")

5 4 3 2 1 Selesai!


In [12]:
for i in range(10):
    if i == 3:
        continue      # lewati iterasi ini, lanjut ke berikutnya
    if i == 7:
        break         # hentikan loop sepenuhnya
    print(i, end=" ")

0 1 2 4 5 6 

---
# Bagian 3 - Function

Function adalah blok kode yang diberi nama supaya bisa dipakai berulang kali.
Dibuat dengan keyword `def`, dan mengembalikan nilai dengan `return`.

In [13]:
def luas_persegi_panjang(panjang, lebar):
    """Menghitung luas persegi panjang."""   # docstring: penjelasan function
    return panjang * lebar

print(luas_persegi_panjang(5, 3))
print(luas_persegi_panjang(lebar=4, panjang=10))   # keyword argument, urutan bebas

15
40


In [14]:
# Default parameter: dipakai kalau argumen tidak diisi
def durasi_audio(jumlah_sample, sample_rate=16000):
    """Menghitung durasi audio (detik) dari jumlah sample."""
    return jumlah_sample / sample_rate

print(durasi_audio(32000))            # pakai default 16000
print(durasi_audio(88200, 44100))     # sample_rate diganti

2.0
2.0


In [15]:
# Function bisa mengembalikan lebih dari satu nilai (dalam bentuk tuple)
def statistik(angka):
    return min(angka), max(angka), sum(angka) / len(angka)

data = [3, 7, 2, 9, 4]
terkecil, terbesar, rata = statistik(data)
print(f"min={terkecil}, max={terbesar}, mean={rata:.2f}")

min=2, max=9, mean=5.00


In [16]:
# lambda: function singkat satu baris, biasanya untuk operasi sederhana
kuadrat = lambda x: x ** 2
print(kuadrat(6))

# sering dipakai bersama map() / sorted()
print(list(map(lambda x: x * 2, [1, 2, 3, 4])))

36
[2, 4, 6, 8]


---
# Bagian 4 - Built-in Data Structure

| Struktur | Sintaks | Terurut | Bisa Diubah | Duplikat |
|---|---|---|---|---|
| **List** | `[ ]` | Ya | Ya | Boleh |
| **Tuple** | `( )` | Ya | **Tidak** | Boleh |
| **Set** | `{ }` | Tidak | Ya | **Tidak** |
| **Dictionary** | `{k: v}` | Ya (Python 3.7+) | Ya | Key unik |

## 4.1 List - koleksi terurut yang bisa diubah

In [17]:
nilai = [80, 95, 70, 88]

nilai.append(90)          # tambah 1 item di akhir
nilai.insert(0, 100)      # sisip di index 0
nilai.remove(70)          # hapus berdasarkan NILAI
terakhir = nilai.pop()    # ambil + hapus item terakhir

print("List     :", nilai)
print("Dihapus  :", terakhir)
print("Panjang  :", len(nilai))
print("Terurut  :", sorted(nilai))
print("Max/Min  :", max(nilai), min(nilai))

List     : [100, 80, 95, 88]
Dihapus  : 90
Panjang  : 4
Terurut  : [80, 88, 95, 100]
Max/Min  : 100 80


In [18]:
# List comprehension: cara ringkas membuat list baru
kuadrat_list = [x ** 2 for x in range(1, 6)]
genap        = [x for x in range(10) if x % 2 == 0]

print("Kuadrat :", kuadrat_list)
print("Genap   :", genap)

Kuadrat : [1, 4, 9, 16, 25]
Genap   : [0, 2, 4, 6, 8]


## 4.2 Tuple - terurut tapi **immutable** (tidak bisa diubah)

In [19]:
koordinat = (3, 5)
x, y = koordinat            # unpacking
print(f"x = {x}, y = {y}")

audio_info = ("speech.wav", 16000, 2.5)
print("Nama file   :", audio_info[0])
print("Sample rate :", audio_info[1])

# audio_info[0] = "lain.wav"   # -> ERROR: tuple tidak bisa diubah

x = 3, y = 5
Nama file   : speech.wav
Sample rate : 16000


## 4.3 Set - koleksi unik, tidak terurut

In [20]:
angka = {1, 2, 3, 3, 2, 1}
print("Duplikat otomatis hilang:", angka)

A = {1, 2, 3, 4}
B = {3, 4, 5, 6}
print("Union        :", A | B)
print("Intersection :", A & B)
print("Difference   :", A - B)

# Trik umum: menghapus duplikat dari list
huruf = ["a", "b", "a", "c", "b"]
print("Unik:", sorted(set(huruf)))

Duplikat otomatis hilang: {1, 2, 3}
Union        : {1, 2, 3, 4, 5, 6}
Intersection : {3, 4}
Difference   : {1, 2}
Unik: ['a', 'b', 'c']


## 4.4 Dictionary - pasangan `key: value`

In [21]:
mahasiswa = {
    "nama"  : "Stanley",
    "nim"   : "2702000000",
    "nilai" : [90, 85, 95]
}

print(mahasiswa["nama"])
print(mahasiswa.get("jurusan", "Tidak ada"))   # .get() aman, tidak error kalau key tak ada

mahasiswa["jurusan"] = "Computer Science"      # tambah key baru
mahasiswa["nama"]    = "Nathanael"             # ubah nilai

print("Keys   :", list(mahasiswa.keys()))
print("Values :", list(mahasiswa.values()))

Stanley
Tidak ada
Keys   : ['nama', 'nim', 'nilai', 'jurusan']
Values : ['Nathanael', '2702000000', [90, 85, 95], 'Computer Science']


In [22]:
# Iterasi dictionary dengan .items()
for key, value in mahasiswa.items():
    print(f"{key:10s}: {value}")

nama      : Nathanael
nim       : 2702000000
nilai     : [90, 85, 95]
jurusan   : Computer Science


---
# Bagian 5 - Slicing

Format: `data[start : stop : step]`
- `start` **termasuk**, `stop` **tidak termasuk**
- index negatif dihitung dari belakang (`-1` = elemen terakhir)

In [23]:
data = [0, 10, 20, 30, 40, 50, 60, 70, 80, 90]
#index  0   1   2   3   4   5   6   7   8   9
#neg  -10  -9  -8  -7  -6  -5  -4  -3  -2  -1

print("data[2:5]   :", data[2:5])     # index 2,3,4
print("data[:4]    :", data[:4])      # dari awal
print("data[6:]    :", data[6:])      # sampai akhir
print("data[::2]   :", data[::2])     # loncat 2
print("data[::-1]  :", data[::-1])    # dibalik
print("data[-3:]   :", data[-3:])     # 3 elemen terakhir

data[2:5]   : [20, 30, 40]
data[:4]    : [0, 10, 20, 30]
data[6:]    : [60, 70, 80, 90]
data[::2]   : [0, 20, 40, 60, 80]
data[::-1]  : [90, 80, 70, 60, 50, 40, 30, 20, 10, 0]
data[-3:]   : [70, 80, 90]


In [24]:
# Slicing juga berlaku untuk string
teks = "Speech Recognition"
print(teks[:6])       # "Speech"
print(teks[7:])       # "Recognition"
print(teks[::-1])     # dibalik
print(teks[0])        # karakter pertama

# Contoh kasus: mengambil 1 detik pertama dari sinyal audio
sinyal_dummy = list(range(48000))       # anggap 3 detik @ 16000 Hz
satu_detik   = sinyal_dummy[:16000]
print("Jumlah sample 1 detik pertama:", len(satu_detik))

Speech
Recognition
noitingoceR hceepS
S
Jumlah sample 1 detik pertama: 16000


---
# Bagian 6 - NumPy: Array, Atribut, & Array Generator

**NumPy** (Numerical Python) adalah library untuk komputasi numerik.
Objek utamanya adalah **ndarray**: array n-dimensi yang jauh lebih cepat dan hemat memori
dibanding list Python biasa.

In [25]:
import numpy as np       # np adalah alias standar
print("NumPy version:", np.__version__)

NumPy version: 2.2.6


## 6.1 `np.array()` - membuat array dari list

In [26]:
arr1d = np.array([1, 2, 3, 4, 5])                  # 1 dimensi (vektor)
arr2d = np.array([[1, 2, 3], [4, 5, 6]])           # 2 dimensi (matriks)

print("1D:", arr1d)
print("2D:")
print(arr2d)
print("Tipe objek:", type(arr1d))

1D: [1 2 3 4 5]
2D:
[[1 2 3]
 [4 5 6]]
Tipe objek: <class 'numpy.ndarray'>


## 6.2 Atribut Array

| Atribut | Arti |
|---|---|
| `.shape` | ukuran tiap dimensi, dalam bentuk tuple |
| `.ndim` | jumlah dimensi |
| `.size` | total jumlah elemen |
| `.dtype` | tipe data elemen |

In [27]:
print("shape :", arr2d.shape)     # (2 baris, 3 kolom)
print("ndim  :", arr2d.ndim)      # 2 dimensi
print("size  :", arr2d.size)      # 2 * 3 = 6 elemen
print("dtype :", arr2d.dtype)     # int64 / int32

shape : (2, 3)
ndim  : 2
size  : 6
dtype : int64


In [28]:
# dtype bisa ditentukan sendiri (penting untuk data audio -> biasanya float32)
arr_float = np.array([1, 2, 3], dtype=np.float32)
print(arr_float, arr_float.dtype)

# reshape: mengubah bentuk tanpa mengubah isinya
a = np.arange(12)              # 0..11
print("Asli  :", a)
print("3x4   :")
print(a.reshape(3, 4))
print("2x2x3 ->", a.reshape(2, 2, 3).shape)
print("-1 artinya hitung otomatis:", a.reshape(4, -1).shape)

[1. 2. 3.] float32
Asli  : [ 0  1  2  3  4  5  6  7  8  9 10 11]
3x4   :
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
2x2x3 -> (2, 2, 3)
-1 artinya hitung otomatis: (4, 3)


## 6.3 Array Generator

Fungsi untuk membuat array tanpa menulis isinya satu per satu.

In [29]:
print("zeros(5) :", np.zeros(5))        # array berisi 0.0
print("ones(4)  :", np.ones(4))         # array berisi 1.0
print("full     :", np.full(4, 7))      # array berisi nilai tertentu

print("\nzeros((2,3)):")
print(np.zeros((2, 3)))                 # 2 dimensi -> shape ditulis sebagai tuple
print("ones((2,3), dtype=int):")
print(np.ones((2, 3), dtype=int))

zeros(5) : [0. 0. 0. 0. 0.]
ones(4)  : [1. 1. 1. 1.]
full     : [7 7 7 7]

zeros((2,3)):
[[0. 0. 0.]
 [0. 0. 0.]]
ones((2,3), dtype=int):
[[1 1 1]
 [1 1 1]]


In [30]:
# empty: mengalokasikan memori TANPA menginisialisasi nilainya.
# Isinya adalah sisa nilai di memori (acak), jadi lebih cepat daripada zeros.
# Gunakan hanya kalau semua elemen pasti akan ditimpa.
kosong = np.empty((2, 3))
print(kosong)

[[5.e-324 5.e-324 5.e-324]
 [5.e-324 5.e-324 5.e-324]]


In [31]:
print("arange(0,10,2)  :", np.arange(0, 10, 2))     # seperti range(), step tetap
print("linspace(0,1,5) :", np.linspace(0, 1, 5))    # 5 titik merata dari 0 s/d 1
print("eye(3):")
print(np.eye(3))                                    # matriks identitas

arange(0,10,2)  : [0 2 4 6 8]
linspace(0,1,5) : [0.   0.25 0.5  0.75 1.  ]
eye(3):
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## 6.4 `np.random` - Array Acak

| Fungsi | Kegunaan |
|---|---|
| `np.random.seed(n)` | mengunci hasil acak agar reproducible |
| `np.random.rand(...)` | acak uniform pada rentang [0, 1) |
| `np.random.randn(...)` | acak dari distribusi normal (mean 0, std 1) |
| `np.random.randint(low, high, size)` | acak bilangan bulat |
| `np.random.choice(list, size)` | ambil acak dari sebuah koleksi |

In [32]:
np.random.seed(42)      # supaya hasilnya sama tiap kali dijalankan

print("rand(3)   :", np.random.rand(3))
print("rand(2,3) :")
print(np.random.rand(2, 3))
print("randn(5)  :", np.random.randn(5))
print("randint   :", np.random.randint(0, 100, size=5))
print("choice    :", np.random.choice(["a", "b", "c"], size=4))

rand(3)   : [0.37454012 0.95071431 0.73199394]
rand(2,3) :
[[0.59865848 0.15601864 0.15599452]
 [0.05808361 0.86617615 0.60111501]]
randn(5)  : [-0.58087813 -0.52516981 -0.57138017 -0.92408284 -2.61254901]
randint   : [48 90 58 41 91]
choice    : ['c' 'b' 'b' 'c']


---
# Bagian 7 - Indexing, Slicing, & Operasi Array

## 7.1 Indexing & Slicing

In [33]:
a = np.arange(10)
print("a       :", a)
print("a[3]    :", a[3])
print("a[2:6]  :", a[2:6])
print("a[::-1] :", a[::-1])

m = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

# Pada array 2D: m[baris, kolom]
print("m[1, 2] (baris 1, kolom 2) :", m[1, 2])
print("m[0]    (baris pertama)    :", m[0])
print("m[:, 1] (kolom ke-1)       :", m[:, 1])
print("m[0:2, 1:3] :")
print(m[0:2, 1:3])

a       : [0 1 2 3 4 5 6 7 8 9]
a[3]    : 3
a[2:6]  : [2 3 4 5]
a[::-1] : [9 8 7 6 5 4 3 2 1 0]
m[1, 2] (baris 1, kolom 2) : 6
m[0]    (baris pertama)    : [1 2 3]
m[:, 1] (kolom ke-1)       : [2 5 8]
m[0:2, 1:3] :
[[2 3]
 [5 6]]


In [34]:
# Boolean masking: menyaring elemen berdasarkan kondisi
data = np.array([12, 5, 30, 8, 25, 3])

print("Kondisi      :", data > 10)
print("Hasil filter :", data[data > 10])
print("Gabungan     :", data[(data > 5) & (data < 30)])

# np.where(kondisi, nilai_jika_benar, nilai_jika_salah)
print("np.where     :", np.where(data > 10, 1, 0))

Kondisi      : [ True False  True False  True False]
Hasil filter : [12 30 25]
Gabungan     : [12  8 25]
np.where     : [1 0 1 0 1 0]


## 7.2 Operasi Elementwise & Broadcasting

Operasi aritmatika pada array dilakukan **per elemen**, tanpa perlu looping (**vectorization**).

In [35]:
x = np.array([1, 2, 3, 4])
y = np.array([10, 20, 30, 40])

print("x + y  :", x + y)
print("x * y  :", x * y)
print("x ** 2 :", x ** 2)
print("x + 100 (broadcasting) :", x + 100)   # skalar disebar ke semua elemen
print("np.sqrt(y) :", np.sqrt(y))

x + y  : [11 22 33 44]
x * y  : [ 10  40  90 160]
x ** 2 : [ 1  4  9 16]
x + 100 (broadcasting) : [101 102 103 104]
np.sqrt(y) : [3.16227766 4.47213595 5.47722558 6.32455532]


In [36]:
# Fungsi agregasi. Parameter axis: 0 = ke bawah (per kolom), 1 = ke samping (per baris)
m = np.array([[1, 2, 3],
              [4, 5, 6]])

print("sum semua     :", m.sum())
print("sum per kolom :", m.sum(axis=0))
print("sum per baris :", m.sum(axis=1))
print("mean / std    :", m.mean(), m.std())
print("max & argmax  :", m.max(), m.argmax())   # argmax = index nilai maksimum

sum semua     : 21
sum per kolom : [5 7 9]
sum per baris : [ 6 15]
mean / std    : 3.5 1.707825127659933
max & argmax  : 6 5


---
# Bagian 8 - Menggabungkan Array

| Fungsi | Arah gabung |
|---|---|
| `np.vstack` | **vertikal** (menumpuk ke bawah / menambah baris) |
| `np.hstack` | **horizontal** (menyambung ke samping / menambah kolom) |
| `np.concatenate` | umum, arah ditentukan lewat `axis` |

In [37]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("vstack -> shape (2, 3):")
print(np.vstack((a, b)))
print("hstack -> shape (6,):", np.hstack((a, b)))

vstack -> shape (2, 3):
[[1 2 3]
 [4 5 6]]
hstack -> shape (6,): [1 2 3 4 5 6]


In [38]:
A = np.array([[1, 2],
              [3, 4]])
B = np.array([[5, 6],
              [7, 8]])

print("vstack (sama dengan concatenate axis=0):")
print(np.vstack((A, B)))
print("\nhstack (sama dengan concatenate axis=1):")
print(np.hstack((A, B)))
print("\nTranspose A (baris <-> kolom):")
print(A.T)

vstack (sama dengan concatenate axis=0):
[[1 2]
 [3 4]
 [5 6]
 [7 8]]

hstack (sama dengan concatenate axis=1):
[[1 2 5 6]
 [3 4 7 8]]

Transpose A (baris <-> kolom):
[[1 3]
 [2 4]]


---
# Studi Kasus Mini: Sinyal Audio Sederhana

Menggabungkan semua materi di atas: membuat gelombang sinus (nada murni),
lalu menghitung statistiknya dan memotongnya menjadi frame - ini adalah bentuk
paling dasar dari pengolahan sinyal suara.

In [39]:
sample_rate = 16000          # jumlah sample per detik
durasi      = 1.0            # detik
frekuensi   = 440            # Hz (nada A)

# t = sumbu waktu: 16000 titik merata dari 0 sampai 1 detik
t = np.linspace(0, durasi, int(sample_rate * durasi), endpoint=False)
sinyal = np.sin(2 * np.pi * frekuensi * t)

print("shape :", sinyal.shape)
print("ndim  :", sinyal.ndim)
print("dtype :", sinyal.dtype)
print("min / max  :", sinyal.min().round(3), sinyal.max().round(3))
print("mean / std :", sinyal.mean().round(3), sinyal.std().round(3))
print("10 sample pertama:", sinyal[:10].round(3))

shape : (16000,)
ndim  : 1
dtype : float64
min / max  : -1.0 1.0
mean / std : 0.0 0.707
10 sample pertama: [0.    0.172 0.339 0.495 0.637 0.76  0.861 0.935 0.982 1.   ]


In [40]:
# Framing: memotong sinyal menjadi frame-frame kecil
# (langkah awal ekstraksi fitur pada speech recognition)
panjang_frame = 400                                   # 400 sample = 25 ms @ 16 kHz
jumlah_frame  = len(sinyal) // panjang_frame

frames = sinyal[:jumlah_frame * panjang_frame].reshape(jumlah_frame, panjang_frame)
print("Shape frames:", frames.shape)                  # (jumlah_frame, panjang_frame)

# Energi tiap frame = rata-rata kuadrat amplitudo (per baris -> axis=1)
energi = (frames ** 2).mean(axis=1)
print("Energi 5 frame pertama:", energi[:5].round(4))

Shape frames: (40, 400)
Energi 5 frame pertama: [0.5 0.5 0.5 0.5 0.5]


---
# Latihan

Kerjakan pada cell di bawah ini.

1. Buat function `konversi_suhu(celsius)` yang mengembalikan nilai Fahrenheit (`F = C * 9/5 + 32`).
2. Dari list `[5, 12, 8, 130, 44, 3]`, gunakan list comprehension untuk mengambil angka yang lebih besar dari 10.
3. Buat dictionary berisi 3 nama mahasiswa beserta nilainya, lalu tampilkan nama dengan nilai tertinggi.
4. Buat array NumPy 4x5 berisi bilangan bulat acak 0-9 (gunakan `np.random.seed(0)`), lalu tampilkan `shape`, `ndim`, dan jumlah nilai per kolom.
5. Buat dua array `np.arange(1, 5)` dan `np.arange(5, 9)`, lalu gabungkan secara vertikal dan horizontal.

In [41]:
# Jawaban No. 1


# Jawaban No. 2


# Jawaban No. 3


# Jawaban No. 4


# Jawaban No. 5

---
## Ringkasan

**Python**
- `print()` untuk output, `input()` untuk input (hasilnya selalu `str`)
- Variable tidak perlu deklarasi tipe; gunakan **f-string** untuk memformat teks
- Blok kode ditentukan oleh **indentasi**, bukan kurung kurawal
- `if / elif / else` untuk percabangan, `for` dan `while` untuk perulangan
- `def` untuk membuat function, `return` untuk mengembalikan nilai
- 4 struktur data: **list** (terurut & mutable), **tuple** (immutable), **set** (unik), **dict** (key-value)
- Slicing `[start:stop:step]` - `stop` tidak ikut, index negatif dihitung dari belakang

**NumPy**
- `np.array()` membuat ndarray; atribut penting: `.shape`, `.ndim`, `.size`, `.dtype`
- Generator: `zeros`, `ones`, `empty`, `full`, `eye`, `arange`, `linspace`, `np.random.*`
- Operasi bersifat **elementwise** + **broadcasting**, jadi tidak perlu looping
- Agregasi (`sum`, `mean`, `std`) memakai `axis=0` (per kolom) atau `axis=1` (per baris)
- `vstack` menumpuk ke bawah, `hstack` menyambung ke samping

Materi ini menjadi dasar untuk sesi berikutnya: pembacaan file audio dan ekstraksi fitur suara.